fix(setups): Adjust pkgs Git build dependencies
Why
These changes make sure that Git builds properly on RHEL 9.6.
Previous setups might have hit errors because of missing dependencies or
incompatible package versions.
This update makes the build process more robust.

Avoid error like:

```log
configure: error: Cannot find a type to use in place of socklen_t, In file
included from /home/upipdfs01/cplx/tools/git/root/usr/include/sys/socket.h:33,
from conftest.c:23:
/home/upipdfs01/cplx/tools/git/root/usr/include/bits/socket.h:384:11:
fatal error: asm/socket.h: No such file or directory
```

What
- Add 'kernel-headers' to the list of Git build requirements.
- Move 'glibc' earlier in the Git build requirement list.
- Change 'kernel-headers' RPM version from 603 to 601.